name: Check code

on: [pull_request, push]

jobs:
  lint_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout reapository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "./requirements_dev.txt"

      - name: Install pip dependencies
        run: pip install -r ./requirements_dev.txt

      - name: Lint code
        run: ruff check .

  test_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout reapository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "./requirements_dev.txt"

      - name: Install pip dependencies
        run: |
          pip install -r ./requirements_dev.txt
          pip install -r ./requirements_prod.txt
      
      - name: Run unit tests
        run: pytest
